version: "3.7"
services:
  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "8501:8501"

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "8000:8000"
    depends_on:
      - frontend
