version: "3.7"
services:
  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "8501:8501"
    volumes:
      - ./shared_folder:/frontend/shared_folder  # Map the shared folder

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./shared_folder:/backend/shared_folder  # Map the shared folder
      - ./demo.png:/backend/demo.png  # Map the demo.png file to the backend service
    depends_on:
      - frontend
