name: Model Pipeline Unittest

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          services: backend

      - name: Execute tests in the running services
        run: |
          docker compose exec backend pytest
